### ISSUE TITLE
could not find ament_cmake

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#92] opened 2022-03-30 16:14 UTC
When I run colcon build ,it appears that CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

**Comment by alsora** [comment] 2022-03-30 16:33
Closing as duplicate of https://github.com/irobot-ros/ros2-performance/issues/83
This issue is unrelated to `ros2-performance`.
You should make sure that your ROS libraries are visible before building

**Closed as completed by alsora** 2022-03-30 16:33 UTC

**Comment by calvinyy-oss** [comment] 2022-03-30 16:53
Thank you！And could you please share the test process with me.I can now run your test model now.But not very clear about how it work!

**Comment by calvinyy-oss** [comment] 2022-03-30 17:05
> What do you mean by test process?

For example the work flow？How this test works.

**Comment by calvinyy-oss** [comment] 2022-03-30 17:38
> What do you mean by test process?

Because I want to have a same test on ROS1 for a comparison.Thank you!

**Comment by alsora** [comment] 2022-03-30 17:52
Sorry, but I;m still not sure what kind of information you want.

You can find here an overview of the measured metrics https://github.com/irobot-ros/ros2-performance/tree/master/irobot_benchmark
You can look at the `performance_metrics` package to see how each metric is measured.
More information on how the project is implemented and the overall design can be found in the README.md documents.

**Comment by calvinyy-oss** [comment] 2022-03-30 22:57
Thank you.And when I get four .txt file,I want to plot them.There is a error:
keyError:'time[ms]'.
And also I am not very clear about the result I get.Could you please describe it! Thank you!

**Comment by alsora** [comment] 2022-03-31 09:20
Please, keep in mind that Github issues are not a discussion forum.
I will not reply further to this issue.

It looks like you had some problems with the plot scripts.
Please open a new issue describing in details what you are doing and what error you are seeing.

About the results, I already pointed you to the appropriate documentation.
If there are parts of the documentation that you think are unclear or that something is missing, please open a separate "issue" with references to what is unclear/wrong/missing.
