### ISSUE TITLE
Plot is empty

### ISSUE THREAD

**Issue by ZhenjiaYY** [irobot-ros/ros2-performance#101] opened 2022-04-06 18:45 UTC
Hi.when I try to plot the results,it's empty.

**Comment by alsora** [comment] 2022-04-06 18:51
Closing as duplicate of https://github.com/irobot-ros/ros2-performance/issues/100.
Before opening an issue, please check if there are already issues that deal with the same situation

**Closed by alsora** 2022-04-06 18:51 UTC
